services:
  dejavu-site:
    image: ghcr.io/taeminhan/dejavu-website:latest
    container_name: dejavu-site
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - f1ti-network

networks:
  f1ti-network:
    external: true
    name: f1ti_default
